# own secrets for each namespace
apiVersion: v1
kind: Secret
metadata:
  name: secret-dockercfg
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: >
    {
      "auths": {
        "reg.toxics.space": {
          "username": "{{ .Values.ownRegistry.user }}",
          "password": "{{ .Values.ownRegistry.pass }}"
        }
      }
    }
